services:
  api:
    build:
      context: ./payment-api
      dockerfile: Dockerfile
    container_name: interswitch-api
    ports:
      - '${API_PORT}:${API_PORT}'
    environment:
      - PORT=${API_PORT}
      - NODE_ENV=${NODE_ENV}
    restart: unless-stopped

  portal:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: interswitch-portal
    ports:
      - '${PORTAL_PORT}:${PORTAL_PORT}'
    environment:
      - PORT=${PORTAL_PORT}
      - NODE_ENV=${NODE_ENV}
      - API_URL=${API_URL}
    depends_on:
      - api
    restart: unless-stopped
    volumes:
      - ./web:/app/web
