name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and Push Docker Image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/interswitch-portal:latest

    - name: Copy Manifests to EC2
      uses: appleboy/scp-action@v0.1.7
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_SSH_KEY }}
        source: "k8s/*"
        target: "/home/ubuntu/interswitch"

    - name: Deploy and Verify on EC2
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          cd /home/ubuntu/interswitch
          sudo k3s kubectl apply -f k8s/
          sudo k3s kubectl set image deployment/portal portal=${{ secrets.DOCKERHUB_USERNAME }}/interswitch-portal:latest
          sudo k3s kubectl rollout status deployment/portal --timeout=150s
          sudo k3s kubectl rollout status deployment/payment-api --timeout=150s
          sudo k3s kubectl get pods -o wide
